### PR TITLE
Manually load entity.info.inc to prevent PHP fatal error.

### PR DESCRIPTION
**Pull request by pcave**
I was getting the error 'call to undefined function entity_entity_property_info()' on line 316 when running the module in a fresh install of Drupal 7.

### CODE REVIEW

**Comment by levelos** [comment]
@pcave, this shouldn't be necessary as entity.info.inc is already automatically loaded by the Entity API module. There might be another underlying issue, although I'm not sure what off hand. We have not run into this yet with 3 devs working on the project. FWIW, we're using Entity API 7.x-1.0-rc3.

**Comment by pcave** [comment]
I'm using 7.x-1.0-rc3 as well, and I see it declared in files[]. Core is 7.16. I agree this shouldn't be needed so I'll dig around some more.

**Comment by pcave** [comment]
@levelos, we've encountered this error in 3 different Drupal 7 sites now. All have the entity api module installed. I also checked the docs on what the files[] array does and it just scans for classes and interfaces. So the module_load_include should still be needed before calling entity_entity_property_info(). You guys probably have something else enabled that has already included that file.

Can this be added?

**Comment by pcave** [comment]
Didn't mean to reopen the whole pull request. I just wanted to make a comment.

**Pull request closed without merging**
