### PR TITLE
Obtain new session id (access token) using Drush

### PR DESCRIPTION
**Pull request by kostajh**
I've added a Drush command (`sf-session-id`) that allows obtaining and setting a new session ID (access token) via Drush. This way, you can use your Salesforce username and password/token to connect with the REST API and bypass the Oauth workflow. There is still some work to do, noted in @TODOs in the code.

For this to work, I changed `getAccessToken()` and `setAccessToken()` to use a variable instead of storing the token in $_SESSION.

Note that `drush-session-id` was branched off of `drush-integration`, so you could merge this request in and it would cover work in both branches.

### CODE REVIEW

**Comment by levelos** [comment]
Just to clarify, what's the intent with using username and password rather than the oauth workflow? The settings on the site will still need to be configured with consumer key and secret. I intentionally stored the access token in session to reflect its ephemeral nature, but that's clearly not a deal breaker.

**Comment by levelos** [comment]
Also, you don't need to make a soap request to gain an access token to the rest API. There's a rest api call that takes consumer key/secret, along with username and password and returns an access token.

**Comment by kostajh** [comment]
If I am using drush to interact with Salesforce, I shouldn't have to interact with Drupal's web interface to authenticate to Salesforce.

What is the REST API call for obtaining the access token? I didn't see that in the Salesforce REST API docs. That would definitely be preferable.

**Comment by levelos** [comment]
If I understand the workflow your imaging correctly, you'd still need to enter the consumer key/secret into the web interface. At that point, you'll already be authorized with oauth anyways, so there shouldn't be a need to pass username and passwords with Drush.

Check out session authorization at http://www.salesforce.com/us/developer/docs/api_rest/index_Left.htm#StartTopic=Content/quickstart_oauth.htm.

**Comment by kostajh** [comment]
"If I understand the workflow your imaging correctly, you'd still need to enter the consumer key/secret into the web interface."

Not necessarily - you could use Drush to set the consumer key / secret using `drush vset`.

But in any case, after thinking about it more - you are right about this, let's leave it out.

**Pull request closed without merging**
